[DllInjector]
AllowMultipleInstancesOfDLLInjector = 0
UseFullPathsFromIni = 0

# Exe to start
Exe = Steam.exe
CommandLine = -inhibitbootstrap

# Dll to inject
Dll = GreenLuma_2026_x64.dll

# Export to call in dll
Export = Init

# Check if call to export returned positive value, debugbreak if not
CheckReturnValue = 0

# Terminate the process when an error is sent from the injected dll
TerminateOnError = 1

# Wait for started exe to close before exiting the DllInjector process.
WaitForProcessTermination = 1

# Set fake parent process
EnableFakeParentProcess = 0
FakeParentProcess = explorer.exe

# Number to files to create
CreateFiles = 0

# Name of the file(s) to create
FileToCreate_1 =
FileToCreate_2 =

BootImage = GreenLuma2026_Files\BootImage.bmp